<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Shared/Source/**/*.cs" LinkBase="Source" />
    <None Include="../Shared/Source/Resource/*.*" LinkBase="Source/Resource" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS0162;CS0169;CS0219;CS0414;CS0618;CS1718;CA2200;CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8619;CS8620;CS8621;CS8625;CS8629;CS8714;CS8765;CS8767</NoWarn>
    <NoWarn>$(NoWarn);SYSLIB0013;SYSLIB0051;SYSLIB0057;</NoWarn>
    <NoWarn>$(NoWarn);NETSDK1138</NoWarn>
    <NoWarn>$(NoWarn);NUnit2005;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CyberSource.Authentication" Version="1.0.0" />
    <PackageReference Include="CyberSource.Rest.Client" Version="1.0.0" />
    <PackageReference Include="jose-jwt" Version="4.1.0" />
  </ItemGroup>
</Project>
